services:
  # LiteLLM server as a dedicated service
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "8008:4000"
    environment:
      - PORT=4000
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - DEFAULT_MODEL=mistralai/devstral-small-2505:free
      - LITELLM_LOG_LEVEL=info  # Changed from debug to reduce log volume
    volumes:
      - ./litellm_config.yaml:/app/config/config.yaml
    command: ["--config", "/app/config/config.yaml", "--port", "4000"]
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:4000/health')"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Add resource constraints
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
      
  # Dedicated RAG service
  rag-service:
    build:
      context: .
      dockerfile: ./src/rag_service/Dockerfile
      # Add build args if needed
      args:
        - BUILDKIT_INLINE_CACHE=1  # Enable BuildKit inline caching
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_API_KEY=${GOOGLE_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - LITELLM_API_BASE=http://litellm:4000
      - MODEL_NAME=${MODEL_NAME:-mistral/devstral-small}
      - DB_DIR=/app/chroma_db
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
    volumes:
      - chroma_data:/app/chroma_db
    depends_on:
      litellm:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Add resource constraints
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
        reservations:
          memory: 1G

  # Streamlit app service
  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: streamlit  # Use the streamlit target from multi-stage build
    ports:
      - "8501:8501"  # For Streamlit app
    volumes:
      - ./src:/app/src  # Mount source code for development
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_API_KEY=${GOOGLE_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - MODEL_NAME=${MODEL_NAME:-mistral/devstral-small}
      - LITELLM_API_BASE=http://litellm:4000
      - RAG_SERVICE_URL=http://rag-service:8000
    depends_on:
      litellm:
        condition: service_healthy
      rag-service:
        condition: service_healthy
    command: streamlit run src/streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    # Add resource constraints
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
  
  # Service for running insert_docs.py with optimized Playwright settings
  crawler:
    build:
      context: .
      dockerfile: ./src/crawler/Dockerfile  # Use the dedicated crawler Dockerfile
    volumes:
      - ./src:/app/src  # Mount source code for development
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_API_KEY=${GOOGLE_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - MODEL_NAME=${MODEL_NAME:-mistral/devstral-small}
      - LITELLM_API_BASE=http://litellm:4000
      - RAG_SERVICE_URL=http://rag-service:8000
      # Playwright specific environment variables
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
    depends_on:
      litellm:
        condition: service_healthy
      rag-service:
        condition: service_healthy
    # Resource constraints - reduced from previous values
    deploy:
      resources:
        limits:
          memory: 4G  # Reduced from 6G
          cpus: '1'   # Reduced from 2 CPUs
        reservations:
          memory: 2G  # Reduced from 3G
    # Increased shared memory size for Playwright
    shm_size: 2gb  # Reduced from 4gb
    # This service doesn't start automatically
    entrypoint: ["python", "src/insert_docs.py"]
    command: ["--help"]  # Default command shows help

volumes:
  chroma_data:  # Named volume for persisting ChromaDB data
