# LiteLLM configuration for multiple model providers
model_list:
  # Gemini models
  - model_name: gemini/gemini-2.0-flash
    litellm_params:
      model: gemini/gemini-2.0-flash
      api_key: "os.environ/GOOGLE_API_KEY"
  
  # Alias for backward compatibility
  - model_name: gemini-2.0-flash
    litellm_params:
      model: gemini/gemini-2.0-flash
      api_key: "os.environ/GOOGLE_API_KEY"
  
  # Mistral model via OpenRouter
  - model_name: mistral/devstral-small
    litellm_params:
      model: openrouter/mistralai/devstral-small:free
      api_key: "os.environ/OPENROUTER_API_KEY"
      api_base: "https://openrouter.ai/api/v1"

litellm_settings:
  drop_params: true
  request_timeout: 30
  verbose: true
  # Enable fallbacks in case of rate limiting or other issues
  success_callback: ["llm_guard"]
  max_retries: 3
  retry_after: 1

general_settings:
  # No master key by default, but you can uncomment and set one if needed
  # master_key: ${LITELLM_MASTER_KEY}
  # Allow all requests without authentication for simplicity
  allow_anonymous_requests: true
  # Logging settings
  log_level: debug
